### PR TITLE
type-hinting and small bug fixes

### PR DESCRIPTION
**Pull request by MarzaElise**
- [x] This is a code change (Improvement, bug fix, new feature)
  - [ ] Bug fix
  - [x] Improvement
  - [x] Feature added
    - PR descripion in the comments  

- [ ] The change is not a code change (ReadMe change, examples add, examples update etc.)
  - [ ] README change
  - [x] Example Change
    - [ ] Added Example
    - [ ] Removed Example
    - [x] Updated Example
      - PR descripion in the comments  
  
- [x] The change are tested
- [x] Change is breaking change

### CODE REVIEW

**Comment by MarzaElise** [comment]
- Type-Hinted almost all of the variables.

- Added docstring for `UnsupportedOperation` error.

- changed some piece of code to look more professional

    - changed `if type(self.joke).__name__ == 'str'` to `if isinstance(self.joke, str)`

- Fixed typo in `examples/jokes.py`

- Now it **actually** raises `TypeError` when the given joke parameter in `utils.format_joke` isnt a `Joke` object

- `get_safe_joke` is now a method of each classes to reduce errors

**Comment by TheGenocides** [comment]
nub soo many indent error
what

**Comment by nerdguyahmad** [comment]
Wow this actually type-hinted everything. This is epic.

**Comment by nerdguyahmad** [comment]
> nub soo many indent error

@TheGenocides That is GitHub commit viewing being gay :trollface:

**Pull request merged**
